.github/workflows/cicd.yml, src/pages/Home.tsx
Resolves: #9 
github actions를 통해 ci/cd를 구축하였습니다.
=> [Chore] CI/CD 구축

src/components/common/Buttons/Button.tsx, src/components/common/routes/PrivateRoute.tsx, src/components/error/boundary/APIErrorFallback.tsx, src/constants/path.ts, src/routes/AppRouter.tsx, src/utils/getErrorData.ts
Resolves: #23 
어떤 변경 사항이 있나요?
sign_in, sign_up 경로의 오타를 수정하였습니다.
=> [Chore] sign_in, sign_up 경로 관련 오타 수정

src/components/layout/Layout.tsx, src/components/layout/header/Header.tsx, src/constants/path.ts, src/pages/about/AboutPage.tsx, src/pages/auth/HelpIdInquiryPage.tsx, src/pages/auth/HelpPwInquiryPage.tsx, src/pages/landing/LandingPage.tsx, src/pages/location/LocationEnterPage.tsx, src/pages/location/LocationRecommendationsPage.tsx, src/pages/location/LocationResultPage.tsx, src/pages/onboarding/OnBoardingPage.tsx, src/pages/place/PlaceCreatePage.tsx, src/pages/place/PlaceResultPage.tsx, src/pages/place/PlaceVotePage.tsx, src/pages/time/TimeCreatePage.tsx, src/pages/time/TimeResultPage.tsx, src/pages/time/TimeVotePage.tsx, src/routes/AppRouter.tsx, src/utils/getAPIResponseData.ts
Resolves: #27 
어떤 변경 사항이 있나요?
- 전체 UI에 대한 경로를 세팅해주었습니다.
- getAPIResponseData라는 함수를 따로 만들어 비동기 요청 과정을 처리하도록 개선하였습니다.
기존의 경우, 비동기 요청시에 try, catch문을 적어주었고, 에러가 발생하게 되면 catch문에서 에러를 반환하는 방식으로 진행하였습니다.
해당 방식의 경우, 매번 비동기 요청을 할때마다 catch문에서는 에러를 리턴하게 되는 코드가 반복되었습니다. (throw e 라는 같은 코드가 계속 반복되었습니다.) 따라서 getAPIResponseData를 통해서 비동기 요청을 처리 하도록 하였고, 해당 함수 내부에서 비동기 요청시에 try, catch문을 사용하여 catch문에서 에러를 반환하도록 하는 방식으로 개선하였습니다. 이후 비동기 요청 함수 작성시에 getAPIResponseData를 사용하여catch문에서 에러를 반환하는 반복되는 과정을 생략할 수 있게 되었습니다.
=> [Chore] UI에 대한 경로 세팅

src/constants/api.ts
Resolves: #29 
swagger를 참고하여 api 경로를 세팅하였습니다.
=> [Chore] api 경로 설정

index.html, src/apis/auth/postSignUp.ts, src/components/common/input/Input.tsx, src/pages/auth/SignUpPage.tsx, src/state/mutations/auth/useSignUpMutation.ts, src/types/auth/SignUpRequestType.ts, src/types/kakaoMap.ts, src/utils/validatePw.ts
Resolves: #40 
회원가입 폼 UI 퍼블리싱
어떤 변경 사항이 있나요?
- input 컴포넌트 생성
- react-hook-form 회원가입 폼
- util validatePw : yup 적용으로 비밀번호, 비밀번호 확인 유효성 검사 스키마
- 회원가입 api, mutate 사용
- 주소검색 : 위도경도 제외 완료 (추후 map 도입되면 추가작성 예정)
페이지-훅-컴포넌트 1대1 이 이런방식인가요?
=> [Feature] 회원가입

src/apis/auth/postSignUp.ts, src/apis/header/getJoinRoom.ts, src/apis/location/deletePlaceDelete.ts, src/apis/location/getPlaceSearch.ts, src/apis/location/patchPlaceUpdate.ts, src/apis/location/postPlaceSave.ts, src/constants/api.ts, src/pages/location/LocationEnterPage.tsx, src/state/mutations/location/usePlaceDeleteMutation.ts, src/state/mutations/location/usePlaceSaveMutation.ts, src/state/mutations/location/usePlaceUpdateMutation.ts, src/state/queries/header/useGetJoinRoomQuery.ts, src/state/queries/location/key.ts, src/state/queries/location/useGetPlaceSearchQuery.ts, src/types/location/placeSaveRequestType.ts, src/types/location/placeSaveResponseType.ts, src/types/location/placeSearchResponseType.ts, src/types/location/placeUpdateRequestType.ts
Resolves: #57 
- 비동기 요청 코드 작성 과정에서 수정,삭제,저장시에 조회 요청시 사용한 쿼리키에 대해 invalidate처리를 하였습니다.
=> [Feature] 중간 지점 장소 입력 부분 api 연동

src/pages/location/LocationEnterPage.tsx, src/pages/place/PlaceCreatePage.tsx, src/pages/place/PlaceVotePage.tsx
Resolves: #67 
장소 투표 생성화면 및 장소 투표 화면을 구현하였습니다.
장소 투표 생성 시에는 모든 장소 필드에 대해서 입력이 되어 있는 경우에 한해서만 투표를 생성할 수 있도록 하였습니다.
장소 투표 하기 화면에서는 선택한 장소가 존재하는 경우에 한해서만 투표를 제출 할 수 있도록 하였습니다.
=> [Design] 장소 투표 생성 및 투표 하기 UI

src/pages/place/PlaceResultPage.tsx
Resolves: #65 
아래의 스크린샷과 같이 장소 투표 결과 UI 퍼블리싱을 완료하였습니다.
=> [Design] 장소 투표 결과 UI 구현

src/components/common/button/Button.tsx, src/components/common/input/Input.tsx, src/components/common/kakao/KakaoLocationPicker.tsx, src/components/onboarding/FunctionOption.tsx, src/components/onboarding/OnBoardingCreate.tsx, src/components/onboarding/OnBoardingPlan.tsx, src/pages/auth/SignInPage.tsx, src/pages/auth/SignUpPage.tsx, src/pages/location/LocationEnterPage.tsx, src/pages/place/PlaceCreatePage.tsx, src/pages/place/PlaceResultPage.tsx, src/pages/place/PlaceVotePage.tsx
Resolves: #95 
기존 form안에서 사용되는 html의 input태그에 대해 이를 공통 Input 컴포넌트를 사용하는 방식으로 수정하여 디자인과 코드의 일관성을 유지하도록 하였습니다. (큰 특이사항이 없어, 공통 Input 컴포넌트가 적절한 곳에 올바르게 사용되었는지 확인해주시면 감사하겠습니다)
=> [Refactor] 공통 Input 컴포넌트를 사용하는 방식으로 수정

src/pages/auth/HelpIdInquiryPage.tsx, src/pages/auth/HelpPwInquiryPage.tsx, src/pages/auth/SignInPage.tsx, src/routes/AppRouter.tsx
Resolves: #80 
아래 첨부한 화면과 같이 비밀번호 찾기 UI 퍼블리싱을 완료하였습니다.
api연동 코드를 제외한 UI 구현만 완료하였습니다. 
추후에 비밀번호 찾기 로직을 고려하여 api 연동을 진행하면 좋을 것 같습니다.
=> [Design] 비밀번호 찾기 페이지 UI 

src/apis/auth/postConfirmEmailVerification.ts, src/apis/auth/postRequestEmailVerification.ts, src/components/auth/constants/index.ts, src/constants/api.ts, src/pages/auth/SignInPage.tsx, src/pages/auth/SignUpPage.tsx, src/state/mutations/auth/useConfirmEmailVerificationMutation.ts, src/state/mutations/auth/useRequestEmailVerificationMutation.ts, src/types/auth/SignUpRequestType.ts, src/types/auth/SignUpSchema.ts, src/types/auth/SignUpVerificationType.ts
=> [Feature] 회원가입/로그인 연동

src/apis/location/getMidpointSearch.ts, src/apis/location/getMidpointTimeSearch.ts, src/components/common/kakao/KakaoMap.tsx, src/components/location/AddressDisplay.tsx, src/components/location/MidpointListItem.tsx, src/components/location/constants/index.ts, src/constants/api.ts, src/hooks/location/useCoordinates.ts, src/pages/location/LocationEnterPage.tsx, src/pages/location/LocationResultPage.tsx, src/state/mutations/location/usePlaceDeleteMutation.ts, src/state/mutations/location/usePlaceSaveMutation.ts, src/state/mutations/location/usePlaceUpdateMutation.ts, src/state/queries/location/key.ts, src/state/queries/location/useMidpointSearchQuery.ts, src/state/queries/location/useMidpointTimeSearchQuery.ts, src/types/location/midpointSearchResponseType.ts, src/types/location/midpointTimeSearchResponseType.ts
Resolves: #85 
api 코드 연동외에 별 다른 특이 사항은 없었습니다. 추가로 코드 작성 과정에서 상위컴포넌트에서는 데이터 처리를 하도록 하였고, 그 아래 하위 컴포넌트에서는 상위컴포넌트에서 받은 데이터를 props로 받아 UI를 담당하도록 하는 방식으로 리팩토링을 진행해주었습니다.
=> [Feature] 중간 지점 결과 화면 api 연동

src/components/common/kakao/KakaoMap.tsx, src/components/location/MidpointListItem.tsx, src/components/location/PlaceItem.tsx, src/hooks/location/useCoordinates.ts, src/pages/location/LocationEnterPage.tsx, src/pages/location/LocationRecommendationsPage.tsx, src/pages/location/LocationResultPage.tsx
=> [Design] 장소 입력 및 카카오 맵 등의 UI 일부 수정

src/apis/place/getPlaceVoteRoomCheck.ts, src/apis/place/postPlaceVoteRoomCreate.ts, src/apis/place/putPlaceVoteRoomUpdate.ts, src/components/common/routes/RoomCheck.tsx, src/components/location/MidpointListItem.tsx, src/components/location/PlaceItem.tsx, src/components/onboarding/OnBoardingPlan.tsx, src/pages/location/LocationEnterPage.tsx, src/pages/location/LocationRecommendationsPage.tsx, src/pages/location/LocationResultPage.tsx, src/pages/place/PlaceCreatePage.tsx, src/state/mutations/place/usePlaceVoteRoomCreateMutation.ts, src/state/mutations/place/usePlaceVoteRoomUpdateMutation.ts, src/state/queries/location/useGetPlaceSearchQuery.ts, src/state/queries/location/useGetRecommendPlaceSearchQuery.ts, src/state/queries/location/useMidpointSearchQuery.ts, src/state/queries/place/key.ts, src/state/queries/place/useGetPlaceVoteRoomCheckQuery.ts, src/types/place/placeVoteRoomCheckResponseType.ts, src/types/place/placeVoteRoomCreateRequestType.ts, src/types/place/placeVoteRoomUpdateRequestType.ts
Resolves: #87
useGetPlaceVoteRoomCheckQuery를 통해 장소 투표방의 생성 여부를 확인하고, 기존에 생성되었다면 응답값으로 목록들을 받아와 보여주었고 투표 재생성하기가 되도록 하였으며, 기존에 생성되지 않았던 경우에는 중간 지점 목록 5개를 받아와 보여주고 투표생성하기가 진행되도록 하였습니다.
투표 생성과정에서 useQuery의 enabled 부분이 적절한지 확인 한 번 부탁드려요!
=> [Feature] 장소 투표 생성 api 연동

src/components/location/MidpointListItem.tsx, src/hooks/location/useCoordinates.ts, src/pages/location/LocationResultPage.tsx
Resolves: #124 
기존의 경우, 나의 위치가 빨간색 마커로, 중간 지점의 좌표가 파란색 마커로 되어 있었으며, 내가 입력한 장소 및 친구들이 입력한 장소에서 중간지점까지의 소요시간과 거리가 올바르게 보이지 않았습니다. 해당 부분에 대해서 선택한 중간 지점 목록에 대해 빨간색 마커가 되도록 변경하였고, 내가 입력한 주소와 친구가 입력한 주소들은 파란색 마커가 되도록 하였으며, 우측에서 중간 지점 목록을 선택할 때마다 내가 입력한 주소와 친구가 입력한 주소들로 부터 중간 지점까지 걸리는 소요시간 및 거리가 보여지도록 하였습니다.
=> [Fix] 중간 지점 결과 화면 로직 수정

src/pages/time/TimeResultPage.tsx, src/pages/time/TimeVotePage.tsx
Resolves: #91
어떤 변경 사항이 있나요?
시간투표 조회 시 existence 가 false 일 경우 somethingWronErrorPage 컴포넌트 렌더링하도록 수정하였습니다.
해당 브랜치로 추가적으로 select 에러 해결 추가해서 커밋하겠습니다.
=> [Fix] 시간 투표, 결과 링크 접속시 제한

src/components/time/voteTime/clickCalendar.tsx, src/components/time/voteTime/datePicker.tsx, src/components/time/voteTime/myVote.tsx, src/pages/time/TimeVotePage.tsx, src/types/time/timeProps.ts
Resolves: #143 pr 에러
어떤 변경 사항이 있나요?
if 문을 쿼리문 하단으로 이동해서 해결했습니다.
최상단에서는 room check 쿼리만 동작하고, 하위 컴포넌트에서 다른 데이터 렌더링해서 에러 발생하지 않고, 방 존재에 대한 검증만 하였습니다.
select 에서 시간을 선택 시 저장하는 서버의 데이터가 한단계씩 밀리는 문제를 확인하였습니다. 데이터를 전달할때 비동기의 문제가 발생하여 마지막 select 의 경우 서버에 반영이 안되는 에러가 발생하였습니다. 컴포넌트 구조화를 많이 적용하였기 때문에 어느곳에서 비동기 문제가 발생하는지 파악하였습니다.
컴포넌트 구조 myVotes- datePicker - TimeSelectBox - Select
총 4 단계에 걸쳐서 onChange 를 감지하고 있었습니다. select option을 직접 전달하고 value 를 직접 감지하는 TimeSelectBox 와 Select 는 문제가 발생하지 않았고, TimeSelectBox 의 변경된 값을 datePicker의 hour, minute 에 set을 하면서 동시에 onChange를 같이 동작하여 비동기로 이전 set 한 값이 onChange로 전달이 되고 있었다는 원인을 파악했습니다.
🚨 문제코드
```js
<TimeSelectBox
initialHour={endHour}
initialMinute={endMinute}
onChange={(hour: string, minute: string) => {
setEndHour(hour);
setEndMinute(minute);
onChange(startHour, …
```
=> [Fix] timevote 렌더링 문제, select 비동기 문제

src/components/users/UserChangePassword.tsx, src/components/users/UserProfileInfo.tsx, src/types/modalType.ts
Resolves: #147 
🚨 [문제 상황]
ErrorPage 컴포넌트에서 "홈으로 돌아가기" 버튼을 클릭했을 때, 단순히 홈 페이지로 이동만 하고 에러 상태는 초기화되지 않았습니다. 이로 인해 사용자가 홈으로 돌아가기 버튼을 클릭한 후에도 여전히 에러 상태가 유지되어, "다시 시도" 버튼을 추가로 클릭해야만 정상적인 홈 화면을 볼 수 있었습니다.
🛠️ [문제 해결 과정]
홈으로 이동하기 전에 에러 상태를 초기화하는 로직을 추가하였습니다.
handleHomeClick 함수 내에서 페이지 이동 전에 onRetry()를 먼저 호출하도록 수정했습니다.
그후 window.location.href을 통해 직접적인 URL 수정을 진행하였습니다.
🎯 [결과]
수정된 코드에서는 "홈으로 돌아가기" 버튼을 클릭하면 onRetry()가 실행되어 에러 상태가 초기화되고 홈 페이지로 이동합니다.
=> [Feature] 에러 동작 수정

.github/workflows/cicd.yml, src/components/auth/oauth/GoogleLogin.tsx, src/components/auth/oauth/KakaoLogin.tsx, src/components/auth/oauth/NaverLogin.tsx, src/components/auth/oauth/Oauth.tsx, src/constants/path.ts, src/hooks/useSocialLogin.ts, src/pages/auth/SignInPage.tsx, src/routes/AppRouter.tsx, src/types/oauthType.ts
Resolves: #150 
카카오, 구글, 네이버에 대한 소셜 로그인 구현을 완료하였습니다.
추후에 백엔드 개발이 완료되면 올바른 백엔드 주소와 login처리가 필요합니다.
=> [Feature] 소셜 로그인 구현

src/components/layout/header/MobileMenu.tsx, src/components/layout/header/MobileMenuList.tsx, src/components/layout/header/MobileSubMenu.tsx, src/components/onboarding/OnBoardingCreate.tsx, src/components/onboarding/OnBoardingFunctionSelect.tsx, src/components/onboarding/OnBoardingPlan.tsx, src/pages/auth/SignUpPage.tsx, tailwind.config.js
Resolves: #159 
아래의 첨부한 사진과 같이 회원가입, 온보딩 로직 과정에 대해서 모바일 UI작업을 완료하였습니다.
=> [Feature] 회원가입 및 온보딩 모바일 UI 작업

src/components/common/kakao/KakaoMap.tsx, src/components/error/boundary/UnknownErrorFallback.tsx, src/components/loading/SearchLocationLoading.tsx, src/components/location/MidpointListItem.tsx, src/pages/location/LocationEnterPage.tsx, src/pages/location/LocationResultPage.tsx
Resolves: #158 
KakaoMap 컴포넌트에서 장소를 추가하거나 삭제할 때마다 coordinates가 변경되면서 모든 마커들이 재생성되고, 이 과정에서 맵이 흔들리면서 마커들이 밀리는 부자연스러운 애니메이션이 발생했습니다.
해당 문제에 대해 기존 마커는 유지하고 새로운 마커만 추가하는 방식으로 로직을 개선했습니다. markersRef를 Map 객체로 관리하여 각 좌표에 대한 마커를 추적하고, 새로운 마커가 맵 영역 밖에 있을 때만 bounds를 재설정하도록 했습니다. 또한 마커 삭제 시에도 남은 마커들이 모두 보이지 않는 경우에만 bounds를 조정하도록 수정했습니다.
결과적으로 장소 추가 시 새로운 마커가 자연스럽게 나타나고, 삭제 시에도 부드럽게 처리되어 사용자 경험이 크게 개선되었습니다. 특히 가까운 위치에 마커를 추가할 때는 맵이 흔들리지 않고, 먼 위치의 마커를 추가하거나 삭제할 때만 필요한 만큼 맵이 조정되어 자연스럽게 보이도록 하였습니다.
=> [Feature] 마커 밀림 현상 개선

src/components/auth/oauth/GoogleLogin.tsx, src/components/auth/oauth/KakaoLogin.tsx, src/components/auth/oauth/NaverLogin.tsx, src/constants/path.ts
=> [Chore] oauth 백엔드 url 설정

src/pages/location/LocationResultPage.tsx
Resolves: #183 
아래와 같이 중간 지점 결과 화면에 대한 모바일 UI 작업을 완료하였습니다.
=> [Design] 중간 지점 결과 화면 모바일 UI

src/components/common/kakao/KakaoMap.tsx, src/pages/place/PlaceVotePage.tsx
Resolves: #187 
기존의 경우, 이전 투표한 목록에 대해서만 빨간 마커로 표시되었습니다. 하지만 내가 어느 위치를 선택하고 있는지에 대해 선택할때마다 카카오맵에 현재 선택한 위치가 반영되지 않아서 아쉬운 점이 있었습니다. 따라서 이전 투표한 장소를 우선하되, 현재 선택되는 장소가 달라질 경우 현재 선택한 장소가 맵에 빨간 마커로 보여지도록 하였습니다.
=> [Design] 장소 투표하기 모바일 UI 구현

src/pages/location/LocationRecommendationsPage.tsx
=> [Design] 중간 지점 장소 추천화면 모바일 UI

src/components/users/UserChangePassword.tsx, src/components/users/UserGroupList.tsx, src/components/users/UserProfile.tsx, src/components/users/UserProfileInfo.tsx, src/components/users/UserQuit.tsx, src/pages/users/UserPage.tsx
=> [Design] 마이페이지 모바일 UI 구현

src/pages/location/LocationEnterPage.tsx
Resolves: #205 
회원정보에 존재하는 주소를 참고하여 주소가 존재하는 경우 장소 입력시에 기본적으로 내가 입력한 장소에 나의 주소가 뜨도록 변경하였습니다.
=> feat: 장소 입력시 기본주소가 뜨도록 개선

src/components/location/Pagination.tsx, src/components/location/PlaceItem.tsx, src/components/time/resultTime/voteResultGrid.tsx, src/components/time/voteTime/VoteResultByDate.tsx, src/components/time/voteTime/clickCalendar.tsx, src/components/time/voteTime/datePicker.tsx, src/components/time/voteTime/myVote.tsx, src/components/time/voteTime/timeSelect.css, src/components/time/voteTime/timeSelectBox.tsx, src/components/users/DesktopSideMenu.tsx, src/components/users/UserChangePassword.tsx, src/components/users/UserProfileInfo.tsx, src/pages/about/AboutPage.tsx, src/pages/location/LocationRecommendationsPage.tsx, src/pages/place/PlaceResultPage.tsx, src/pages/time/TimeCreatePage.css, src/pages/time/TimeCreatePage.tsx, src/pages/time/TimeResultPage.tsx, src/pages/time/TimeVotePage.tsx
Resolves: #214
어떤 변경 사항이 있나요?
- 중간지점 내가 입력한 장소에 기존저장이 없어도, 기본적으로 흰 박스 한개가 열려있을 수 있도록
- 모임상세 모달 펜슬 svg 색상
- 카테고리 영어 -> 한국어
- 투표정보 없을때 돌고래
- 투표하기 로딩 ui
=> design: 디자인 QA

index.html, src/hooks/share/useKakaoShare.ts
어떤 변경 사항이 있나요?
깃허브 팀 명 변경에 따라 이미지 링크가 깨져서, 업데이트 하면서
SEO 설정도 추가해주었습니다.
=> [Fix] 깃허브 이미지 주소 변경, SEO 공유 태그 설정
