syncspot-team/Syncspot-FE

- src/components/common/kakao/KakaoMap.tsx
- src/pages/location/LocationEnterPage.tsx
- src/types/mapAPIType.ts
Resolves: #51 
카카오맵이 포함된 웹 페이지에서 브라우저 창의 크기를 조절할 때, 특히 너비를 빠르게 줄였다가 다시 늘리는 경우 맵의 일부가 제대로 표시되지 않는 문제가 발생했습니다. 이는 카카오맵의 특성상 컨테이너 크기가 변경될 때 내부 레이아웃을 수동으로 재조정해야 하는데, 리사이징 이벤트 발생 시 적절한 타이밍에 맵 레이아웃이 업데이트되지 않아 발생한 현상이었습니다.
처음에는 단순히 resize 이벤트에서 카카오맵의 relayout() 메서드를 호출하고 바로 bounds를 재설정하는 방식을 시도했으나, 빠른 리사이징 시에는 제대로 동작하지 않았습니다. 이는 리사이징 이벤트가 매우 빈번하게 발생하고, 맵의 레이아웃 재조정이 비동기적으로 이루어지는데 충분한 시간이 주어지지 않았기 때문이라고 생각했습니다. 따라서 이를 해결하기 위해 디바운스 패턴을 적용하여 리사이징 이벤트를 200ms 간격으로 제한하고, relayout() 호출 후 bounds 재설정 전에 100ms의 추가 지연시간을 부여하는 방식으로 문제를 해결했습니다. 
해당 과정은 resizeTimeoutRef라는 useRef를 사용하여 구현했습니다. 리사이즈 이벤트가 발생할 때마다 이전 타임아웃을 clearTimeout으로 취소하고, 새로운 타임아웃을 setTimeout으로 설정하는 방식으로, 연속된 리사이즈 이벤트 중 마지막 이벤트만 실행되도록 제어했습니다. 200ms와 100ms라는 수치는 여러 번의 실험을 통해 결정되었는데, 200ms는 사용자의 리사이즈 동작이 완료되기를 기다리는 시간으로, 테스트 과정에서 지연을 거의 느끼지 …
> [Fix] 맵 렌더링 관련 에러 해결 

- src/components/common/button/SearchButton.tsx
- src/components/common/kakao/KakaoLocationPicker.tsx
- src/pages/auth/SignUpPage.tsx
- src/pages/location/LocationEnterPage.tsx
Resolves: #53 
기존 handleLocationSelect 함수는 void 타입을 반환하도록 설계되어 있었는데, 이는 장소 중복 검사 시 중복된 장소가 발견되더라도 KakaoLocationPicker의 UI에 선택된 장소가 그대로 표시되는 문제가 있었습니다. 이를 개선하기 위해 handleLocationSelect 함수가 boolean 값을 반환하도록 변경하였고, 중복된 장소가 발견될 경우 false를 반환하여 KakaoLocationPicker의 handlePlaceSelect 함수에서 이 값을 확인할 수 있게 했습니다. 이렇게 함으로써 중복된 장소 선택 시 setSelectedLocation이 호출되지 않아 UI에 선택된 장소가 표시되지 않게 되었고, 장소가 중복되었음을 토스트 메시지를 통해 알릴 수 있도록 하였습니다.
> [Feature] 장소 입력 로직 수정

- src/components/layout/header/Header.tsx
- src/components/layout/header/HeaderMenu.tsx
- src/components/layout/header/RoomList.tsx
Resolves: #81 
초기에는 마우스를 올려놓았을 경우에 세부 메뉴가 나오도록 구현하였지만, 모바일을 고려하여 클릭시에 세부 메뉴가 나오도록 하는 방식으로 결정하였습니다.
전체 모임 목록 맨 아래에 "전체 모임 보기" 부분을 추가하였고, 해당 부분이 맨 아래 고정되도록 position: sticky를 사용하여 적용하였습니다.
> [Feature] 네이게이션 메뉴 드롭다운

- src/pages/landing/LandingPage.tsx
- src/pages/location/LocationEnterPage.tsx
- src/pages/onboarding/OnBoardingPage.tsx
#102 
온보딩 페이지는 세 가지 단계(PLAN → CREATE → FUNCTION_SELECT)로 구성되어 있으며, 각 단계별 전환은 다음과 같이 동작했습니다
1. 사용자가 랜딩 페이지에서 "모임 장소 찾으러 가기" 버튼 클릭 → /onboarding 경로로 이동하여 PLAN 단계 진입
2. PLAN 단계에서 "모임 추가" 버튼 클릭 → setOnboardingStep(CREATE_STEP)으로 CREATE 단계로 전환
3. CREATE 단계에서 모임 생성 완료 → setOnboardingStep(FUNCTION_SELECT_STEP)으로 FUNCTION_SELECT 단계로 전환
이때 각 단계 전환은 단순히 React의 state(onboardingStep)만을 변경하여 관리하고 있었습니다. 이로 인해 브라우저의 뒤로가기 버튼을 클릭했을 때, React state는 그대로 유지된 채 이전 페이지(온보딩 진입 전 페이지)로 이동하는 문제가 발생했습니다. 예를 들어, PLAN → CREATE → (뒤로가기) 시 CREATE 단계의 state는 유지된 채로 온보딩 이전 페이지로 이동하여, 사용자가 기대하는 동작(CREATE → PLAN)과 실제 동작이 불일치하는 문제 상황이 있었습니다.
기존 코드에서는 단계 전환 시 단순히 React state만 업데이트하고 있었습니다.
브라우저의 history stack에는 각 단계별 상태가 제대로 저장되지 않아 뒤로가기 시 이전 페이지로 이동하는 문제가 발생했습니다.
브라우저의 History API(pushState, replaceState)를 활용하여 각 단계별 상태를 …
> [Bug] 온보딩 단계에 따른 뒤로가기 문제 해결

- src/assets/icons/IconXmark.svg
- src/pages/location/LocationEnterPage.tsx
- src/pages/location/LocationRecommendationsPage.tsx
- src/pages/place/PlaceCreatePage.tsx
Resolves: #105 
이 과정에서 ResizeObserver를 도입하여 useEffect 내에서 요소의 scrollWidth와 clientWidth를 비교하는 방식으로 구현하였습니다. 주소 팝업 컴포넌트를 별도로 분리하고, 상태 관리를 위해 단일 값 대신 Set 자료구조를 도입하여 expandedAddressIds로 여러 팝업의 상태를 독립적으로 관리하였습니다. 또한 AddressElement 컴포넌트에서는 useRef를 활용하여 DOM 요소를 참조하고, ResizeObserver를 통해 화면 크기 변경을 실시간으로 감지하여 반응형 디자인을 구현하였습니다.
> [Feature] 상세주소를 아래에 컴포넌트로 띄우도록 수정

- src/apis/common/getJoinedRoomCheck.ts
- src/components/common/kakao/KakaoLocationPicker.tsx
- src/components/common/routes/RoomCheck.tsx
- src/components/layout/RoomLayout.tsx
- src/components/layout/header/RoomList.tsx
- src/pages/auth/SignUpPage.tsx
- src/pages/location/LocationEnterPage.tsx
- src/pages/location/LocationRecommendationsPage.tsx
- src/pages/location/LocationResultPage.tsx
- src/pages/place/PlaceCreatePage.tsx
- src/routes/AppRouter.tsx
- src/state/queries/common/key.ts
- src/state/queries/common/useGetJoinedRoomCheckQuery.ts
- src/state/queries/location/useGetPlaceSearchQuery.ts
- src/types/common/joinedRoomCheckResponseType.ts
Resolves: #116 
기존의 경우, url에 존재하는 roomId에 대해서 다른 roomId를 입력하여 변경하여도 RoomList에서 방 목록의 이름을 제대로 반영하지 못하는 문제점이 있었습니다. 이 문제를 해결하기 위해 RoomList 컴포넌트를 확인한 결과, url에 있는 roomId의 변경을 고려하는 코드가 존재하지 않고 있다는 것을 확인하였습니다. 따라서 이 부분에 대해서 useEffect의 의존성 배열에 url에 있는 roomId값을 추가하여, url 변경시에도 알맞은 방 이름으로 매핑되도록 하여 버그를 해결하였습니다.
``` javascript
const { roomId: urlRoomId } = useParams();
... 
if (urlRoomId && roomList?.data) {
const roomFromUrl = roomList.data.find(
(room: IRoom) => room.roomId === urlRoomId,
);
if (roomFromUrl) {
setRoomId(roomFromUrl.roomId);
setRoomName(roomFromUrl.roomName);
setSelectedRoomName(roomFromUrl.roomName);
return;
}
}
```
url에 방 Id가 존재할때, 해당 방에 회원이 아닌 회원의 경우 해당 방에 회원으로 저장하는 과정을 수행하였습니다. (초대기능이 따로 없기에 사용자가 방 링크로 접속할때 방 회원이 아닌 경우, 방에 해당 회원을 저장하는 과정이 필요합니다.)
따라서 roomId가 url에 존재하는 컴포넌트 (중간 …
> [Feature] 중간 지점 장소 입력 api 연동

- src/apis/location/getRecommendPlaceSearch.ts
- src/components/common/kakao/KakaoMap.tsx
- src/components/location/AddressDisplay.tsx
- src/components/location/MidpointListItem.tsx
- src/components/location/Pagination.tsx
- src/components/location/PlaceItem.tsx
- src/components/location/PlaceList.tsx
- src/components/location/PlaceTypeFilter.tsx
- src/components/location/constants/index.ts
- src/pages/location/LocationRecommendationsPage.tsx
- src/pages/location/LocationResultPage.tsx
- src/state/mutations/location/usePlaceDeleteMutation.ts
- src/state/mutations/location/usePlaceSaveMutation.ts
- src/state/mutations/location/usePlaceUpdateMutation.ts
- src/state/queries/location/key.ts
- src/state/queries/location/useGetRecommendPlaceSearchQuery.ts
- src/types/location/recommendPlaceSearchResponseType.ts
Resolves: #86 
사용자가 웹 애플리케이션에서 카테고리 필터(전체/스터디/카페/식당)를 변경할 때마다 새로운 데이터를 서버로부터 불러오고 화면을 업데이트해야 했습니다. 데이터는 성공적으로 불러와졌지만, 각 장소를 나타내는 아이콘이 즉각적으로 업데이트되지 않는 문제가 발생했습니다. 예를 들어, '식당' 카테고리에서 '스터디' 카테고리로 변경했을 때, 새로운 스터디 장소 목록은 표시되지만 여전히 식당 아이콘이 표시되는 현상이 있었습니다. 이는 비동기 데이터 패칭과 React의 상태 업데이트 간의 타이밍 불일치로 인해 발생한 문제였습니다.
처음에는 handlePlaceStandardChange 함수 내에서 상태 업데이트(setSelectedPlaceStandard)와 데이터 리페치(refetch())를 동시에 처리하려 했습니다. 이 과정에서 async/await를 사용했지만, React의 상태 업데이트 생명주기와 맞지 않아 UI 업데이트가 제대로 이루어지지 않았습니다. 이는 React의 상태 업데이트가 배치(batch) 처리되는 방식과 비동기 작업의 완료 시점이 일치하지 않아 발생한 문제였습니다.
다음으로, 아이콘 렌더링 로직을 조건부 렌더링으로 변경하여 문제를 해결하려 했습니다. selectedPlaceStandard === 'ALL' || selectedPlaceStandard === place.placeStandard 조건을 추가하여 선택된 카테고리에 맞는 아이콘만 표시되도록 했지만, 여전히 상태 업데이트와 데이터 리페치 간의 타이밍 문제가 해결되지 않았습니다.
최종적으로 React의 관심사 분리를 …
> [Feature] 장소 추천 화면 api 연동

- src/apis/place/getPlaceVoteLookup.ts
- src/apis/place/postPlaceVote.ts
- src/apis/place/putPlaceRevote.ts
- src/pages/place/PlaceCreatePage.tsx
- src/pages/place/PlaceVotePage.tsx
- src/state/mutations/place/usePlaceRevoteMutation.ts
- src/state/mutations/place/usePlaceVoteMutation.ts
- src/state/mutations/place/usePlaceVoteRoomUpdateMutation.ts
- src/state/queries/place/key.ts
- src/state/queries/place/useGetPlaceVoteLookupQuery.ts
- src/types/place/placeRevoteRequestType.ts
- src/types/place/placeVoteLookupResponseType.ts
- src/types/place/placeVoteRequestType.ts
Resolves: #88 
아래와 같은 로직을 통해 장소 투표하기 연동을 진행하였습니다.
1. 장소 투표방 조회하기를 통해 장소 투표방의 존재 여부를 확인
2. 장소 투표방 X
- SomethingWentWrongPage 컴포넌트 렌더링 (추후에 장소 투표방을 생성하라는 UI로 대체하면 좋을 것 같습니다.)
3. 장소 투표방 O
3.1 장소 투표 여부 및 투표 항목 조회
- 투표 X
- 투표하기로 요청
- 투표 O
- 투표한 목록에 대해 선택된 UI를 보여준다.
- 재투표하기로 요청
장소 투표 로직이 적합한지 확인해주시면 감사하겠습니다.
> [Feature] 장소 입력하기 api 연동

- src/apis/place/getPlaceVoteResult.ts
- src/pages/place/PlaceResultPage.tsx
- src/state/mutations/place/usePlaceRevoteMutation.ts
- src/state/mutations/place/usePlaceVoteMutation.ts
- src/state/mutations/place/usePlaceVoteRoomUpdateMutation.ts
- src/state/queries/place/key.ts
- src/state/queries/place/useGetPlaceVoteResultQuery.ts
- src/types/place/placeVoteResultResponseType.ts
Resolves: #89 
먼저 장소 투표방 조회하기 api를 통해 투표방의 존재여부를 확인하였습니다.
- 투표방 X
-  SomethingWentWrogPage 렌더링 (추후에 장소 투표방을 만들거나, 장소를 입력하라는 UI를 렌더링 하면 더 도움이 될 것 같습니다.)
- 투표방 O
- 투표결과를 받아 투표 득수에 따라 내림차순 정렬하여 보여주었습니다.
- 추가로, 투표하기, 재투표하기, 장소 투표방 재생성시에 투표 결과 조회가 invalidate되도록 처리하였습니다.
> [Feature] 장소 투표 결과화면 api 연동

- src/apis/auth/postPwReissue.ts
- src/apis/auth/postPwReissueEmailVerification.ts
- src/components/auth/PwInquiryStep.tsx
- src/components/auth/PwReissueStep.tsx
- src/constants/api.ts
- src/pages/auth/HelpPwInquiryPage.tsx
- src/state/mutations/auth/usePwReissueEmailVerificationMutation.ts
- src/state/mutations/auth/usePwReissueMutation.ts
- src/types/auth/PwReissueEmailVerificationRequestType.ts
- src/types/auth/PwReissueRequestType.ts
- src/utils/getErrorData.ts
Resolves: #94 
연동 과정중에 임시 비밀번호가 응답 데이터로 오는 것이 아닌, 앞서 입력해주었던 이메일로 발송되는 것으로 확인했습니다.
따라서 기존에는 임시비밀번호를 화면에 보여주는 과정으로 진행했다면, 이후에는 임시비밀번호가 기존에 입력한 이메일로 발송되었다고 알려주는 UI를 띄웠습니다.
또한 비밀번호 찾기 과정중, 이메일을 입력하지도 않았는데 임시코드 필드가 있는 것이 부자연스러워 이메일을 입력하고 이메일 인증이 올바르게 처리되었다면 임시코드 필드가 보여지도록 수정하였습니다.
수정 부분이 적절한지 확인 부탁드립니다.
> [Feature] 비밀번호 찾기 api 연동

- src/apis/users/patchModifyPassword.ts
- src/components/common/modal/PasswordChangeModal.tsx
- src/components/users/DesktopSideMenu.tsx
- src/components/users/UserChangePassword.tsx
- src/components/users/UserProfile.tsx
- src/components/users/UserProfileImage.tsx
- src/components/users/UserProfileInfo.tsx
- src/components/users/UserQuit.tsx
- src/constants/api.ts
- src/pages/users/UserPage.tsx
- src/state/mutations/user/useModifyPasswordMutations.ts
- src/types/users/modifyPasswordRequestType.ts
Resolves: #130 
크게 논의해볼 사항은 없는 것 같습니다! 
리팩토링 과정에서 컴포넌트로 하나하나 분리하는 대신 선언형 함수를 만들어 처리하였습니다. (그 이유는 컴포넌트로 분리했을때, 유사한 컴포넌트가 비밀번호 변경, 프로필 등등에도 여러곳에서 쓰이는데 이때 디자인이 각각 달라서 컴포넌트로 분리하는 장점이 없다고 판단하였기 때문입니다.) 이 방법이 괜찮은지? 코드가 한눈에 들어오는지 궁금합니다.
비밀번호 수정 로직 확인 한 번 부탁드립니다.
> [Feature] 비밀번호 변경 api 연동

- src/apis/users/deleteQuitUser.ts
- src/components/users/UserGroupList.tsx
- src/components/users/UserProfileImage.tsx
- src/components/users/UserQuit.tsx
- src/constants/api.ts
- src/state/mutations/user/useQuitUserMutation.ts
- src/types/users/quitUserRequestType.ts
Resolves: #93 
회원탈퇴 부분 과정에서 스웨거를 참고했을때 RequestBody에 탈퇴 이유가 아닌 accessToken이 있는 점에 대해 슬랙에 올려놨습니다.
추가로 {accessToken: ""}로 요청을 보내도 회원이 탈퇴되고 있어서 이 부분도 함께 슬랙에 올려두었습니다.
> [Feature] 회원탈퇴 및 전체 모임 목록 연동

- src/apis/onboarding/deleteUserFromRoom.ts
- src/apis/onboarding/getRoomDetailInfo.ts
- src/components/common/modal/RoomDetailInfoModal.tsx
- src/components/onboarding/modal/EditableField.tsx
- src/components/users/UserQuit.tsx
- src/constants/api.ts
- src/hooks/header/useMenuItems.ts
- src/pages/auth/SignUpPage.tsx
- src/pages/location/LocationRecommendationsPage.tsx
- src/state/mutations/onboarding/useDeleteUserFromRoomMutation.ts
- src/state/queries/header/key.ts
- src/state/queries/header/useGetCheckLocationEnterQuery.ts
- src/state/queries/header/useGetPlaceVoteRoomExistsQuery.ts
- src/state/queries/header/useGetPlaceVotedQuery.ts
- src/state/queries/header/useGetTimeViteRoomExistsQuery.ts
- src/state/queries/header/useGetTimeVotedQuery.ts
- src/types/auth/SignUpSchema.ts
- src/types/users/quitUserRequestType.ts
Resolves: #135 
1. 장소 입력 - 항상 보여야함
2. 결과 화면 - 해당 방에 장소가 입력된 경우에만 보여야함. 즉 나 또는 내 친구가 장소를 입력한 경우에만 메뉴에 떠야함 - 나 또는 내 친구가 모두 입력을 하지 않았다면 SomethingWentWrongPage 보여주기
3. 추천 화면 - 해당 방에 장소가 입력된 경우에만 보여야함. 즉 나 또는 내 친구가 장소를 입력한 경우에만 메뉴에 떠야함 - 나 또는 내 친구가 모두 입력을 하지 않았다면 SomethingWentWrongPage 보여주기
1. 장소 투표 생성 - 항상 보여야함 + 장소 투표방 조회하기에서 존재한다면 장소 투표 재생성으로 보이도록 + 그렇지 않다면 장소 투표하기로 보이도록
2. 장소 투표하기 - 해당 방에 투표가 생성된 경우에만 메뉴에 떠야함 + 내가 아직 투표를 안했다면 투표하기 + 내가 투표를 했다면 재투표하기가 떠야함
3. 장소 투표 결과 - 해당 방에 투표가 생성된 경우에만 메뉴에 떠야함
1. 시간 투표 생성
2. 시간 투표하기
3. 시간 투표 결과
헤더 로직이 적절한지 확인 부탁드립니다.
> [Chore] 백엔드 api 변동사항 반영

- src/apis/users/getUserInfo.ts
- src/apis/users/getUserPresignedUrl.ts
- src/apis/users/getUserProfileImage.ts
- src/apis/users/patchUserAddress.ts
- src/apis/users/patchUserNickName.ts
- src/components/common/modal/RoomDetailInfoModal.tsx
- src/components/users/UserChangePassword.tsx
- src/components/users/UserGroupList.tsx
- src/components/users/UserProfile.tsx
- src/components/users/UserProfileImage.tsx
- src/components/users/UserProfileInfo.tsx
- src/constants/api.ts
- src/state/mutations/onboarding/useDeleteUserFromRoomMutation.ts
- src/state/mutations/user/usePatchUserAddressMutation.ts
- src/state/mutations/user/usePatchUserNickNameMutation.ts
- src/state/queries/header/useGetJoinRoomQuery.ts
- src/state/queries/users/key.ts
- src/state/queries/users/useGetUserInfoQuery.ts
- src/state/queries/users/useGetUserProfileImageQuery.ts
- src/types/onboarding/deleteUserFromRoomRequestType.ts
- src/types/users/getUserInfoResponseType.ts
- src/types/users/getUserPresignedUrlResponseType.ts
- src/types/users/getUserProfileImageResponseType.ts
- src/types/users/modifyUserAddressRequestType.ts
- src/types/users/modifyUserNicknameRequestType.ts
- src/utils/getErrorData.ts
Resolves: #138 
방 상세 버튼 클릭을 통해 방에 대한 상세정보 모달이 뜨게 됩니다. 이때 모달 아래에 있는 모임 나가기 버튼을 통해 모임이 나가지도록 구현 하였습니다.
개인정보 수정 버튼을 통해 닉네임 및 주소 수정이 가능하도록 하였습니다. UserProfileInfo 컴포넌트가 처음 렌더링 될때, useGetUserInfoQuery훅을 통해 서버로 부터 회원 정보를 받아와 이를 useState로 관리되는 initialNickname, initialAddress 변수에 저장하였습니다. 이후 수정과정에서 입력한 값이 초기 저장된 회원정보와 달려졌을 경우 서버로 수정 요청을 보내 수정이 이루어지도록 하였습니다.
presigned 방식을 통해 프로필 사진 연동을 진행하였습니다.
사용자가 이미지를 변경할때, input의 onChange에서 파일의 변경을 감지합니다. 이후 서버로 부터 presigned url을 요청하고 응답으로 받은 presigned url을 사용하여 put방식으로 이미지를 업로드하였습니다. 이미지가 변경된 이후에는 사용자의 이미지 url을 불러오는 요청인 useGetUserProfileImageQuery에 대해 refetch를 진행하여 즉각적으로 반영이 되도록 하였습니다.
1️⃣ 모임 나가기 연동 
2️⃣ 회원 정보 조회 및 수정 (닉네임, 주소) 연동
> [Feture] 추가 백엔드 api 연동 작업

- src/components/users/UserChangePassword.tsx
- src/components/users/UserProfileInfo.tsx
- src/types/modalType.ts
#146 
비밀번호 UI 부분의 input에 placeholder를 추가하였습니다.
또한 기존 버튼의 너비가 위의 input과 맞지 않는 문제가 있었습니다. form에서 lg:max-w-[40rem]를 지정해주었고, 버튼 컴포넌트에 w-full을 주어 해결하였습니다.
기존의 경우, 수정 버튼을 클릭하여 수정을 한 뒤에 완료가 아닌 취소 버튼을 누르게 되면 초기에 받아온 값이 아닌 수정된 값이 보이는 문제가 있었습니다. 이 부분은 취소 버튼시에 초기 데이터로 변경하지 않아서 발생한 문제였습니다. 따라서 사용자가 취소 버튼을 누르게 될 경우, 닉네임과 주소 부분에 대해서 초기에 받아온 데이터로 다시 변경되도록 하였습니다.
> [BUG] 프로필 수정 중 에러 해결

- src/components/common/kakao/KakaoLocationPicker.tsx
- src/state/mutations/auth/useSignUpMutation.ts
Resolves: #157 
KakaoLocationPicker 컴포넌트에서 두 가지 주요 문제가 발생했습니다:
1.  사용자가 특정 장소(ex. 이대역 2호선)를 선택한 후 다른 장소를 검색하려고 할 때, 이전에 선택했던 장소가 검색 결과에 순간적으로 나타났다가 사라지는 UI 깜빡임 현상이 발생했습니다.
2. 일부 장소(ex. 광교호수공원)가 검색 추천 목록에는 표시되지만, 실제 선택 시 주소 정보 조회(searchAddressInfo)가 실패하면서 400 에러가 발생하는 문제가 있었습니다. 이는 유효하지 않은 장소가 추천 목록에 포함되어 있었기 때문입니다.
두 가지 문제를 다음과 같이 해결했습니다
1. UI 깜빡임 문제
handlePlaceSelect 함수에서 장소 선택 시 즉시 setSuggestions([]) 호출하도록 하였으며 handleInputChange 함수에서 입력값 유효성 검사 로직 개선하였습니다.
2. 유효하지 않은 장소 추천 문제
searchPlaces 함수에서 각 장소에 대해 미리 searchAddressInfo API를 호출하여 주소 정보 확인하였습니다. 즉 도로명 주소를 기반으로 주소를 찾고자 할때 해당 주소가 존재하는 경우에 대해서만 추천 목록에 뜨도록 미리 처리하였습니다.
> [Fix] 장소 검색에 에러 해결

- src/components/common/kakao/KakaoMap.tsx
- src/components/common/modal/Modal.tsx
- src/components/place/PlaceCreateErrorPage.tsx
- src/components/place/PlaceVoteErrorPage.tsx
- src/pages/about/AboutPage.tsx
- src/pages/location/LocationEnterPage.tsx
- src/pages/place/PlaceCreatePage.tsx
- src/pages/place/PlaceVotePage.tsx
- src/state/queries/location/useMidpointSearchQuery.ts
Resolves: #164 
처음 온보딩 과정에서 모임을 생성한 후, "중간 지점 찾기" , "장소 투표" ,"시간 투표" 중에 "장소 투표" 를 선택하게 되는 경우, 해당 모임에 입력한 장소가 없기때문에 해당 방에 장소를 입력하도록 하는 과정이 필요합니다. 따라서 해당 방에 입력된 장소가 없는 채로 장소 투표 url에 들어가는 경우, 해당 방에 입력된 장소가 없다면 장소를 입력하도록 하는 UI를 포함하였습니다.
> [Fix] 장소투표 로직 관련 에러 해결 

- src/components/common/bottomSheet/BottomSheet.tsx
- src/hooks/useBottomSheet.ts
- src/pages/location/LocationEnterPage.tsx
Resolves: #177 
바텀 시트 구현을 위해 2개의 파일(useBottomSheet.ts, BottomSheet.ts)를 만들었습니다.
useBottomSheet 훅을 사용하여 실제 UI를 구현하도록 하였고 백분율 기반의 높이 설정(minHeight, maxHeight, initialHeight)을 통해 반응형으로 보이도록 하였습니다. 컴포넌트는 드래그 가능한 핸들, 백드롭(배경 오버레이), 그리고 콘텐츠 영역으로 구성하였고 heightStyle을 dvh 단위로 변환하여 적용함으로써 모바일 브라우저의 동적 UI 변화에 반응하도록 하였습니다. 또한 isCollapsed 상태에 따라 백드롭을 표시하거나 숨기는 기능을 제공하였습니다.
이 훅은 바텀시트의 핵심 동작 로직을 담당하고, dvh 기반으로 설계하였습니다. 퍼센트 단위(0-100%)로 받은 높이값을 실제 화면 크기에 맞게 dvh로 변환하여 처리하며, 드래그 이벤트를 통해 바텀시트의 높이를 동적으로 조절하도록 하였습니다. 특히 모바일 환경에서 브라우저 UI 요소(주소창, 하단 바 등)가 나타나거나 사라질 때도 안정적으로 동작하도록 resize 이벤트를 감지하여 높이를 재계산하도록 하였습니다.
아래의 스크린샷을 참고해주세요. (코드의 경우는 리팩토링시 모바일, 데스크탑으로 분리하여 적용예정입니다.)
바텀 시트 구현 부분 확인 부탁드려요! (useBottomSheet.ts, BottomSheet.tsx)
> [Design] 중간 지점 입력 모바일 UI

- src/components/layout/header/MobileMenu.tsx
- src/components/time/voteTime/clickCalendar.tsx
- src/components/time/voteTime/datePicker.tsx
- src/components/time/voteTime/myVote.tsx
- src/pages/time/TimeCreatePage.tsx
- src/pages/time/TimeVotePage.tsx
- src/state/mutations/time/usePutTimeRoomMutation.ts
- src/styles/global.css
Resolves: #174
어떤 변경 사항이 있나요?
🚨 시간투표 드롭다운 렌더링 에러
기존 투표값이 있는 경우, 다시 값을 변경하면 onChange 가 동작하는데, 다시 기존투표값으로 덮어씌워지는 문제 발생
✅ 초기값 세팅하는 useEffect 의 키를 전체 투표정보(업데이트 포함) 으로 설정하지 않고, 초기데이터인 myVote.memberAclidableStartTime 과 EndTime으로 설정하여 덮어씌워지는 문제를 해결하였습니다.
https://github.com/user-attachments/assets/6c429f16-19db-49fb-b856-e65a5a3e4d4d
🚨 시작 시간, 끝 시간 검증
시작 시간이 끝나는 시간보다 늦을 경우, 투표하지 않고 return 하는 검증을 추가하였습니다. 비교 시 Date 객체를 사용해서 시간 비교 정확도를 높였습니다.
```js
const hasInvalidTime = votes.some((vote) => {
const startTime = new Date(vote.memberAvailableStartTime);
const endTime = new Date(vote.memberAvailableEndTime);
return startTime >= endTime;
});
if (hasInvalidTime) {
CustomToast({
type: 'error',
message: '시작 시간이 종료 시간보다 늦을 수 없습니다.',
});
return;
}
```
🚨 캘린더 초기 표시되는 월
캘린더는 오늘 날짜가 포함된 월을 기본적으로 표시하고 있었습니다.
선택한 …
> [Fix] 시간 투표값 드롭다운 변경 에러 해결

- src/components/common/bottomSheet/BottomSheet.tsx
- src/components/layout/header/RoomList.tsx
- src/hooks/useBottomSheet.ts
- src/pages/location/LocationEnterPage.tsx
- src/pages/place/PlaceCreatePage.tsx
- src/state/mutations/place/usePlaceVoteMutation.ts
- src/state/mutations/place/usePlaceVoteRoomCreateMutation.ts
Resolves: #186 
아래의 스크린샷 참고 부탁드려요
기존의 경우, 바텀시트의 최소 높이에만 상단에 있는 헤더 메뉴들을 선택할 수 있도록 설계하였습니다. ( 바텀시트가 기본높이 이상이 되는 경우에는 사용자는 바텀시트 내부 로직에 집중하고 있다고 생각하였기 때문. + 바텀시트가 최대로 높이 올라갔을 경우 헤더등을 가릴수도 있다고 생각하였기 때문). 하지만 바텀시트의 최대 높이는 헤더까지 가지 않도록 UI가 나왔기때문에 이를 고려하여 바텀시트의 높이에 상관없이 헤더 메뉴 (로고, 방목록, 햄버거 메뉴) 등에 대해 선택가능하도록 하였습니다.
찾아주신 에러과정이 올바르게 처리되었는지 확인부탁드립니다.
> [Design] 장소 투표 생성 모바일 UI

- src/components/common/modal/QuitModal.tsx
- src/components/users/UserGroupList.tsx
- src/components/users/UserQuit.tsx
- src/pages/place/PlaceCreatePage.tsx
- src/pages/place/PlaceResultPage.tsx
- src/pages/place/PlaceVotePage.tsx
- src/types/modalType.ts
Resolves: #195 
기존의 경우, 계정 탈퇴하기 버튼 클릭시에 바로 계정이 탈퇴가 되었습니다. 하지만 계정 탈퇴의 중요한 사항의 경우 사용자로부터 한 번더 묻는 과정을 통해 계정 탈퇴의 과정의 신중함을 더해야한다고 생각하여 계정 탈퇴하기시에 모달을 통해 정말 계정을 삭제할 것 인지 한 번더 확인하도록 하였습니다.
> [Feature] 계정 삭제시 한번 더 묻도록 개선

- src/components/common/bottomSheet/BottomSheet.tsx
- src/components/time/resultTime/gridTime.tsx
- src/components/time/resultTime/voteResultGrid.tsx
- src/components/time/utils/formatTime.ts
- src/components/time/voteTime/VoteResultByDate.tsx
- src/components/time/voteTime/clickCalendar.tsx
- src/components/time/voteTime/datePicker.tsx
- src/components/time/voteTime/myVote.tsx
- src/components/time/voteTime/timeSelect.css
- src/components/time/voteTime/timeSelect.tsx
- src/components/time/voteTime/timeSelectBox.tsx
- src/pages/time/TimeResultPage.tsx
- src/pages/time/TimeVotePage.tsx
- src/types/modalType.ts
- src/types/time/timeProps.ts
Resolves: #175 
어떤 변경 사항이 있나요?
1️⃣ 투표결과 헤더너비 맞춤, 모바일뷰 적용시 그리드 12 -> 6 단위로 재계산
모바일 버전 시 컴포넌트를 교체해야하기 때문에 브라우저 크기를 새로고침 없이 바로 반영할 수 있는 `window.addEventListener('resize')` 옵션을 사용하였습니다.
2️⃣ 투표하기 바텀시트, 캘린더 클릭
🚨 useBottomSheet.ts  67 Line
~~렌더링 에러 발생~~ **해결**
```
TimeVotePage.tsx:35 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
at BottomSheet (http://localhost:3000/src/components/common/bottomSheet/BottomSheet.tsx:20:3)
```
TimeVotePate.tsx 의 onHeightChange 사용방법이 맞는지 확인 부탁드립니다.
> [Design] 모바일 UI 시간 투표하기 바텀시트, 투표결과 그리드
